action:
  consumption_action:
    enabled: false
    max: 100.0
    min: -100.0
  multi_action: false
  production_action:
    enabled: false
    max: 100.0
    min: -100.0

# Observation space configuration
observation_space:
  battery_level:
    min: "from_battery_config"  # Will use battery min from battery config
    max: "from_battery_config"  # Will use battery max from battery config
  time:
    min: 0.0
    max: 1.0
  iso_buy_price:
    min: 10.0
    max: 50.0
  iso_sell_price:
    min: 10.0
    max: 50.0

# Default ISO agent parameters
default_iso_params:
  quadratic:
    buy_a: 1.0
    buy_b: 2.0
    buy_c: 5.0

# Dispatch cost configuration
dispatch_cost:
  thresholds:
    - level: 100.0
      rate: 5.0
    - level: 170.0
      rate: 7.0
    - level: "inf"
      rate: 8.0

battery:
  dynamic_type: model_based
  model_parameters:
    charge_efficiency: 1.0
    charge_rate_max: 10.0
    discharge_efficiency: 1.0
    discharge_rate_max: 10.0
    init: 30.0
    lifetime_constant: 100.0
    max: 1000.0
    min: 0.0
  model_type: deterministic_battery

consumption_unit:
  dynamic_type: model_based
  model_parameters:
    consumption_capacity: 0.0
    peak_consumption1: 0.0
    peak_consumption2: 0.0
    peak_time1: 0.25
    peak_time2: 0.75
    width1: 1.0
    width2: 1.0
  model_type: deterministic_consumption

production_unit:
  dynamic_type: model_based
  model_parameters:
    peak_production: 0.0
    peak_time: 0.0
    production_capacity: 0.0
    width: 1.0
  model_type: deterministic_production

# Background autonomous processes within PCS (not affecting system demand)
background_processes:
  - name: solar
    type: production
    interval: 1.0      # once per day at midday
    quantity: 5.0
    start_time: 15
    end_time: 25

  - name: hvac morning
    type: consumption
    interval: 0
    quantity: 0
    start_time: 0   
    end_time: 0    

  - name: hvac evening
    type: consumption
    interval: 0      
    quantity: 0
    start_time: 0  
    end_time: 0    

