name: Run Unit Tests

on:
  pull_request:
    branches: [main]  # or any branch you want to protect

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]  # assuming you have [test] in setup.cfg

    - name: Run tests
      run: |
        pytest  # or your test command